/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"
#include "timer.h"
#include "pwm.h"

//Timer
static Timer_t g_ledTimer;   //Part a, b
static Timer_t g_shotTimer;  //Part d

//Part a
static void LED_ToggleCallback(void)
{
    uint8_t *led_output_register = ((uint8_t *)&(GPIOE->ODR)) + 1;
    *led_output_register ^= (1 << 0);   //Toggle PE8 to represent periodic timer
}

//Part d
static void OneShotCallback(void)
{
    uint8_t *led_output_register = ((uint8_t *)&(GPIOE->ODR)) + 1;
    *led_output_register ^= (1 << 1);   //Toggle PE9 once to represent one-shot
}

//Systick interrupt every 100 us
void SysTick_Handler(void)
{
    Timer_Tick(&g_ledTimer);
    Timer_Tick(&g_shotTimer);
    Servo_Tick();
}

static void enable_clocks(void)
{
    //GPIOA (servo pin PA5), GPIOE (LEDs PE8-PE15)
    RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOEEN;
}

static void initialise_board(void)
{
    //Configure PE8-PE15 as outputs: 0x5555 = 0101 0101 0101 0101
    //Sets MODER bits to 01 (output) for each of PE8-PE15
    uint16_t *led_output_registers = ((uint16_t *)&(GPIOE->MODER)) + 1;
    *led_output_registers = 0x5555;
    //PA5 output is configured in pwm.c
}

int main(void)
{
    enable_clocks();
    initialise_board();
    SysTick_Config(8000000U / 10000U);

    //Part a
    Timer_Init(&g_ledTimer, 250U, LED_ToggleCallback);

    //Part b
    uint32_t current_period = Timer_GetPeriod(&g_ledTimer);
    (void)current_period;

    //Set 500 ms for current countdown
    Timer_SetPeriod(&g_ledTimer, 500U);

    //Part c
    Servo_Init();
    Servo_SetPulse(SERVO_PULSE_CENTRE_US); //1500 us: centre

    //Part d
    Timer_OnceMs(&g_shotTimer, 12000U, OneShotCallback);

    //Loop
    for (;;) {
        __WFI(); //Wait until next 100 us SysTick
    }
}
